package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Автоматизация заполнения формы(demoqa).")
    void generatedTest() {
        step("Открыть https://demoqa.com/automation-practice-form", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле First Name(Anton)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Last Name (Gorodetskiy)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Email (Anton.Gorodetskiy@mail.com)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Gender (Male)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Mobile (9296112233)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Date of Birth (01 Aug 1982)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Subject (Social Studies, Accounting)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить чекбокс Hobbies (Sports, Music)", () -> {
            step("// todo: just add selenium action");
        });

        step("Добавить картинку Picture (0.ДЗ.png)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле Current Address (Karnal Bus Stand)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле State(Haryana)", () -> {
            step("// todo: just add selenium action");
        });

        step("Заполнить поле City (Karnal)", () -> {
            step("// todo: just add selenium action");
        });

        step("Отправить форму (Submit)", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить успешную отправку (содержание формы ответа).", () -> {
            step("// todo: just add selenium action");
        });

        step("Закрыть форму (Close)", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://demoqa.com/automation-practice-form'", () ->
            open("https://demoqa.com/automation-practice-form"));

        step("Page title should have text 'ToolsQA'", () -> {
            String expectedTitle = "ToolsQA";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://demoqa.com/automation-practice-form'", () ->
            open("https://demoqa.com/automation-practice-form"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}